# Cloud Build configuration for task-manager-web frontend
steps:
  # Validate workspace structure
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'validate-structure'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔍 Validating task-manager-web structure..."
        ls -la
        echo "Checking frontend Dockerfile..."
        if [ ! -f "Dockerfile" ]; then
          echo "❌ Frontend Dockerfile not found!"
          exit 1
        fi
        echo "Checking package.json..."
        if [ ! -f "package.json" ]; then
          echo "❌ package.json not found!"
          exit 1
        fi
        echo "✅ All required files found"

  # Test Frontend Build
  - name: 'node:18'
    id: 'test-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔧 Installing dependencies..."
        npm ci
        echo "🧪 Testing frontend build..."
        npm run build || echo "⚠️  Build failed but continuing for debugging"
    env:
      - 'NEXT_PUBLIC_API_URL=https://adhd-task-manager-api-371157983914.europe-west4.run.app'
      - 'NEXTAUTH_URL=https://adhd-task-manager-web-371157983914.europe-west4.run.app'
    waitFor: ['validate-structure']

  # Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '--cache-from'
      - 'europe-west4-docker.pkg.dev/project-leonel/adhd-task-manager/adhd-task-manager-web:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://adhd-task-manager-api-371157983914.europe-west4.run.app'
      - '--build-arg'
      - 'NEXTAUTH_URL=https://adhd-task-manager-web-371157983914.europe-west4.run.app'
      - '-t'
      - 'europe-west4-docker.pkg.dev/project-leonel/adhd-task-manager/adhd-task-manager-web:$SHORT_SHA'
      - '-t'
      - 'europe-west4-docker.pkg.dev/project-leonel/adhd-task-manager/adhd-task-manager-web:latest'
      - '.'
    waitFor: ['test-frontend']

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west4-docker.pkg.dev/project-leonel/adhd-task-manager/adhd-task-manager-web'
    waitFor: ['build-frontend']

  # Deploy to production
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-production'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying frontend to production..."
        gcloud run deploy adhd-task-manager-web \
          --image=europe-west4-docker.pkg.dev/project-leonel/adhd-task-manager/adhd-task-manager-web:$SHORT_SHA \
          --region=europe-west4 \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars="NODE_ENV=production,NEXT_PUBLIC_API_URL=https://adhd-task-manager-api-371157983914.europe-west4.run.app,NEXTAUTH_URL=https://adhd-task-manager-web-371157983914.europe-west4.run.app" \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=20 \
          --timeout=900 \
          --concurrency=1000
        
        echo "✅ Frontend deployed to production"
        echo "🌐 URL: https://adhd-task-manager-web-371157983914.europe-west4.run.app"
    waitFor: ['push-frontend']

  # Send notification
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'notify'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "✅ Frontend build and deployment completed!"
        echo "🚀 Image: europe-west4-docker.pkg.dev/project-leonel/adhd-task-manager/adhd-task-manager-web:$SHORT_SHA"
        echo "🌐 Production URL: https://adhd-task-manager-web-371157983914.europe-west4.run.app"
        echo "📊 View logs: https://console.cloud.google.com/run/detail/europe-west4/adhd-task-manager-web"
    waitFor: ['deploy-production']

# Fix the service account logging issue
options:
  # Use CLOUD_LOGGING_ONLY to avoid bucket configuration requirements
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

timeout: '1200s'
